FROM rust

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    bison \
    clang \
    flex \
    git \
    git-core \
    libclang-dev \
    libncurses-dev \
    lld \
    llvm

ENV USER_NAME dev
ARG host_uid=1000
ARG host_gid=1000
RUN groupadd -g $host_gid $USER_NAME && \
    useradd -g $host_gid -m -s /bin/bash -u $host_uid $USER_NAME

USER dev

WORKDIR /home/dev

RUN rustup component add rust-src
RUN cargo install --locked --version 0.56.0 bindgen
